---
name: Container

on:
    push:
        branches:
            - 'develop\+ct'
        paths-ignore:
            - 'doc/**'
    pull_request:
        branches:
            - 'develop\+ct'
        paths-ignore:
            - 'doc/**'


env:
    REGISTRY: ghcr.io
    IMAGE_TAG: nightly

jobs:
    build:
        name: Build images
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: 'adopt'
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2

            - name: Build container images
              run: mvn -Pct package -Dct.build.tag="${IMAGE_TAG}" -Dct.build.registry="${REGISTRY}"

            - name: Upload dataverse-k8s image as artifact
              uses: ishworkh/docker-image-artifact-upload@v1
              with:
                  image: gdcc/dataverse-k8s:${{ env.IMAGE_TAG }}
            - name: Upload solr-k8s image as artifact
              uses: ishworkh/docker-image-artifact-upload@v1
              with:
                  image: gdcc/solr-k8s:${{ env.IMAGE_TAG }}
    scan:
        name: Security Scan - Dataverse image
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read

        steps:
            - name: Download Dataverse image
              uses: ishworkh/docker-image-artifact-download@v1
              with:
                  image: gdcc/dataverse-k8s:${{ env.IMAGE_TAG }}
            - name: Scan Dataverse Container Image for vulnerabilities
              # https://github.com/aquasecurity/trivy-action
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: gdcc/dataverse-k8s:${{ env.IMAGE_TAG }}
                  format: template
                  template: '@/contrib/sarif.tpl'
                  severity: CRITICAL,HIGH
                  ignore-unfixed: true
                  output: trivy-results.sarif
            - name: Upload scan results as SARIF report to GitHub Security Tab
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: trivy-results.sarif
    push:
        name: Push images
        needs: scan
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        # Only push images to registry if this is not a PR
        if: ${{ github.event_name == 'push' }}
        steps:
            - name: Download Dataverse image from artifacts
              uses: ishworkh/docker-image-artifact-download@v1
              with:
                  image: gdcc/dataverse-k8s:${{ env.IMAGE_TAG }}
            - name: Download Solr image from artifacts
              uses: ishworkh/docker-image-artifact-download@v1
              with:
                  image: gdcc/solr-k8s:${{ env.IMAGE_TAG }}
            - name: Log in to the Container registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: 'adopt'
            - name: Push Docker image
              run: mvn -Pct docker:push -Dct.build.tag="${IMAGE_TAG}" -Dct.build.registry="${REGISTRY}"
