---
name: Container

on:
    push:
        branches:
            - 'master\+ct'
        paths-ignore:
            - 'doc/**'


env:
    REGISTRY: ghcr.io
    # Will be set in a step below, but for safety, set it here.
    IMAGE_TAG: latest

jobs:
    build-scan-push:
        name: Build, Scan, Push images
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: 'adopt'
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Get image tag from Maven release property
              run: echo "IMAGE_TAG=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

            - name: Build container images
              run: mvn -Pct package -Dct.build.tag="${IMAGE_TAG}" -Dct.build.registry="${REGISTRY}"

            - name: Scan Dataverse Container Image for vulnerabilities
              # https://github.com/aquasecurity/trivy-action
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: gdcc/dataverse-k8s:${{ env.IMAGE_TAG }}
                  format: template
                  template: '@/contrib/sarif.tpl'
                  severity: CRITICAL,HIGH
                  ignore-unfixed: true
                  output: trivy-results.sarif
            - name: Upload scan results as SARIF report to GitHub Security Tab
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: trivy-results.sarif

            - name: Log in to the Container registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Docker image
              run: mvn -Pct docker:push -Dct.build.tag="${IMAGE_TAG}" -Dct.build.registry="${REGISTRY}"
