---
name: Container Images

on:
    - push
    - pull_request
    # TODO: maybe add timer based trigger here to push most recent builds.

env:
    REGISTRY: ghcr.io
    IMAGE_TAG: nightly

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: 'adopt'
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2

            - name: Build images
              run: mvn -Pct package -Dct.build.tag="${IMAGE_TAG}" -Dct.build.registry="${REGISTRY}"

            - name: Log in to the Container registry
              uses: docker/login-action@v1
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop+ct' }}
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Docker image
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop+ct' }}
              run: mvn -Pct docker:push -Dct.build.tag="${IMAGE_TAG}" -Dct.build.registry="${REGISTRY}"