name: Reviewdog
on:
    pull_request:
        paths:
            - "conf/container/Dockerfile"
            - "conf/solr/Dockerfile"
jobs:
    hadolint:
        name: Hadolint (Dockerfile linting)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: hadolint
              uses: reviewdog/action-hadolint@v1
              with:
                  github_token: ${{ secrets.github_token }}
                  reporter: github-pr-review # Default is github-pr-check